AWSTemplateFormatVersion: 2010-09-09
Description: 'Resources for running the AccountAuditConfiguration contract tests'
Resources:
  RoleForDeviceDefenderAudit:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "iot.amazonaws.com"
            Action:
              - "sts:AssumeRole"

Outputs:
  RoleForDeviceDefenderAuditOutput:
    Value:
      Fn::GetAtt: [RoleForDeviceDefenderAudit, Arn]
    Export:
      Name: RoleForDeviceDefenderAuditArn
  AccountIdOutput:
    Value:
      Fn::Sub: "${AWS::AccountId}"
    Export:
      Name: AccountId
